#!/usr/bin/openrc-run

depend() {
        use net
}

start() {
        ebegin "Starting darkhttpd"
        mkdir -p $DARKHTTPD_PIDDIR && chown jenkins $DARKHTTPD_PIDDIR
        start-stop-daemon --start --exec /usr/bin/darkhttpd -- ${DARKHTTPD_OPTS} --pidfile $DARKHTTPD_PID
        eend $?
}

stop() {
        ebegin "Stopping darkhttpd"
        start-stop-daemon --stop --quiet --pidfile $DARKHTTPD_PID
        eend $?
}
